version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16-bullseye
    steps:
      - checkout

      - run:
          name: Show current directory
          command: pwd

      - run:
          name: List all files recursively
          command: ls -R

      - run:
          name: List specific files
          command: |
            ls -l index.html script.js styles.css || echo "Files missing"

      - run:
          name: Check node and npm versions
          command: |
            node -v
            npm -v

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
